name: connectax_ui_kit
description: Connectax UI Kit.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_svg: ^1.1.1+1
  font_awesome_flutter: ^10.1.0
  bitsdojo_window: ^0.1.2
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf